// lib/data.ts - All product data and categories
import { Product } from './store';

export const categories = [
  { id: 'pain-relief',    name: 'Pain Relief',   icon: '💊', color: 'from-rose-400 to-rose-600',     bg: 'bg-rose-50',   count: 48 },
  { id: 'skincare',       name: 'Skincare',       icon: '🧴', color: 'from-amber-400 to-orange-500',  bg: 'bg-amber-50',  count: 62 },
  { id: 'vitamins',       name: 'Vitamins',       icon: '🌿', color: 'from-emerald-400 to-green-600', bg: 'bg-emerald-50', count: 91 },
  { id: 'cold-flu',       name: 'Cold & Flu',     icon: '🤧', color: 'from-blue-400 to-blue-600',     bg: 'bg-blue-50',   count: 35 },
  { id: 'dental',         name: 'Dental Care',    icon: '🦷', color: 'from-cyan-400 to-teal-600',     bg: 'bg-cyan-50',   count: 27 },
  { id: 'first-aid',      name: 'First Aid',      icon: '🩹', color: 'from-red-400 to-red-600',       bg: 'bg-red-50',    count: 44 },
  { id: 'womens-health',  name: "Women's Health", icon: '🌸', color: 'from-pink-400 to-pink-600',     bg: 'bg-pink-50',   count: 38 },
  { id: 'mens-health',    name: "Men's Health",   icon: '💪', color: 'from-indigo-400 to-indigo-600', bg: 'bg-indigo-50', count: 29 },
];

export const products: Product[] = [
  {
    id: '1',
    name: 'Omega-3 Fish Oil 1000mg',
    brand: 'NutriCore',
    price: 18.99,
    originalPrice: 24.99,
    rating: 4.8,
    reviews: 2341,
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&q=80',
    category: 'vitamins',
    badge: 'Best Seller',
    description: 'Premium quality Omega-3 fatty acids sourced from wild-caught fish. Supports heart, brain, and joint health.',
    inStock: true,
  },
  {
    id: '2',
    name: 'Vitamin D3 + K2 Drops',
    brand: 'SunVital',
    price: 22.49,
    originalPrice: 29.99,
    rating: 4.7,
    reviews: 1856,
    image: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400&q=80',
    category: 'vitamins',
    badge: 'New',
    description: 'Advanced formula combining D3 and K2 for maximum calcium absorption and bone health.',
    inStock: true,
  },
  {
    id: '3',
    name: 'Ibuprofen 400mg Tablets',
    brand: 'PharmaPlus',
    price: 6.49,
    rating: 4.6,
    reviews: 4201,
    image: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=400&q=80',
    category: 'pain-relief',
    description: 'Fast-acting anti-inflammatory pain relief for headaches, muscle pain, and fever.',
    inStock: true,
  },
  {
    id: '4',
    name: 'Hydrating Serum SPF 50+',
    brand: 'DermaClear',
    price: 34.99,
    originalPrice: 44.99,
    rating: 4.9,
    reviews: 987,
    image: 'https://images.unsplash.com/photo-1556228578-567ba127e37f?w=400&q=80',
    category: 'skincare',
    badge: 'Premium',
    description: 'Lightweight, non-greasy formula with hyaluronic acid and broad-spectrum SPF protection.',
    inStock: true,
  },
  {
    id: '5',
    name: 'Probiotic Complex 50B CFU',
    brand: 'GutHealth+',
    price: 29.99,
    originalPrice: 39.99,
    rating: 4.7,
    reviews: 1432,
    image: 'https://images.unsplash.com/photo-1559181567-c3190100191f?w=400&q=80',
    category: 'vitamins',
    badge: 'Sale',
    description: '10 clinically studied strains for optimal digestive balance and immune support.',
    inStock: true,
  },
  {
    id: '6',
    name: 'Cold & Flu Relief Capsules',
    brand: 'Lemsip Pro',
    price: 8.99,
    rating: 4.5,
    reviews: 3102,
    image: 'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=400&q=80',
    category: 'cold-flu',
    description: 'Multi-symptom relief for nasal congestion, sore throat, and fever.',
    inStock: true,
  },
  {
    id: '7',
    name: 'Electric Toothbrush Pro',
    brand: 'OralCare Elite',
    price: 49.99,
    originalPrice: 79.99,
    rating: 4.8,
    reviews: 756,
    image: 'https://images.unsplash.com/photo-1559591937-a04e98bb47c6?w=400&q=80',
    category: 'dental',
    badge: 'Best Value',
    description: 'Sonic technology with 5 cleaning modes, pressure sensor, and 2-minute timer.',
    inStock: true,
  },
  {
    id: '8',
    name: 'Magnesium Glycinate 400mg',
    brand: 'SleepWell',
    price: 16.99,
    rating: 4.6,
    reviews: 2089,
    image: 'https://images.unsplash.com/photo-1631651363392-f14fe929a0f7?w=400&q=80',
    category: 'vitamins',
    description: 'Highly bioavailable magnesium for muscle relaxation, sleep quality, and stress relief.',
    inStock: true,
  },
  {
    id: '9',
    name: 'Collagen Peptides Powder',
    brand: 'BeautyBoost',
    price: 38.99,
    originalPrice: 49.99,
    rating: 4.7,
    reviews: 1234,
    image: 'https://images.unsplash.com/photo-1573461160327-1f1ea4f05745?w=400&q=80',
    category: 'skincare',
    badge: 'New',
    description: 'Hydrolyzed type I & III collagen for skin elasticity, hair, and nail strength.',
    inStock: true,
  },
  {
    id: '10',
    name: 'First Aid Kit Deluxe',
    brand: 'SafeGuard',
    price: 24.99,
    rating: 4.8,
    reviews: 892,
    image: 'https://images.unsplash.com/photo-1603398938378-e54eab446dde?w=400&q=80',
    category: 'first-aid',
    description: '85-piece comprehensive first aid kit in a durable waterproof case.',
    inStock: true,
  },
  {
    id: '11',
    name: "Women's Multivitamin Pack",
    brand: 'FemVital',
    price: 19.99,
    originalPrice: 26.99,
    rating: 4.6,
    reviews: 1678,
    image: 'https://images.unsplash.com/photo-1616671276441-2f2c277b8bf6?w=400&q=80',
    category: 'womens-health',
    badge: 'Popular',
    description: 'Complete daily nutrition tailored for women, including folate, iron, and biotin.',
    inStock: true,
  },
  {
    id: '12',
    name: 'Zinc + Vitamin C Effervescent',
    brand: 'ImmuneShield',
    price: 9.99,
    rating: 4.5,
    reviews: 3456,
    image: 'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=400&q=80',
    category: 'vitamins',
    description: 'Effervescent tablets for daily immune support with 1000mg Vitamin C and 10mg Zinc.',
    inStock: false,
  },
];

export const testimonials = [
  {
    id: 1,
    name: 'Sarah Mitchell',
    role: 'Regular Customer',
    avatar: 'SM',
    rating: 5,
    text: 'Absolutely fantastic service. My order arrived the very next day and everything was packaged beautifully. The product quality is exceptional — I\'ve been ordering my vitamins here for 2 years now.',
  },
  {
    id: 2,
    name: 'Dr. James Patel',
    role: 'GP, NHS',
    avatar: 'JP',
    rating: 5,
    text: 'I recommend PharmaPlus to my patients regularly. The pharmacy is fully licensed, prices are competitive, and the clinical team is responsive. Genuine peace of mind for patients.',
  },
  {
    id: 3,
    name: 'Emma Thompson',
    role: 'Verified Buyer',
    avatar: 'ET',
    rating: 5,
    text: 'The dark mode on the website is gorgeous and the checkout is the smoothest I\'ve experienced on any pharmacy site. Super fast delivery and well-priced products. 10/10.',
  },
  {
    id: 4,
    name: 'Marcus Williams',
    role: 'Fitness Coach',
    avatar: 'MW',
    rating: 4,
    text: 'Great selection of sports supplements and vitamins. The filter system makes it so easy to find exactly what I need. Will definitely be a loyal customer.',
  },
];

export function cn(...classes: (string | undefined | false | null)[]) {
  return classes.filter(Boolean).join(' ');
}
